name: 'Delete untagged ghcr'
author: 'Chuzkiyahu Raful'
description: 'Delete containers on github container registry without tags'
branding:
  icon: 'trash-2'
  color: 'blue'
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      needs delete:packages permissions
    required: true
  repository-owner:
    description: 'The repository owner name'
    default: ${{ github.repository_owner }}
    required: false
  repository-name:
    description: 'Delete only from repository name'
    default: ""
    required: false
  package-name:
    description: 'Delete only from package name'
    required: false
    default: ""
  owner-type:
    description : "Owner type (org or user)"
    required: true
    options:
      - org
      - user
  dry-run:
    description: "Run the script without making any changes."
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Run registry cleaner
      shell: bash
      run: |
        args="--token ${{ inputs.token }} "
        args+="--dry-run ${{ inputs.dry-run }} "
        args+="--repo-owner ${{ inputs.repository-owner }} "
        args+="--repo-name ${{ inputs.repository-name }} "
        args+="--package-name ${{ inputs.package-name }} "
        args+="--owner-type ${{ inputs.owner-type }}"
        echo "args: $args"
        python ${{ github.action_path }}/action.py $args
